apiVersion: v1
kind: ConfigMap
metadata:
  name: actions-runner-config-map
  namespace: development
data:
  values.yaml: |-
    githubConfigUrl: "https://github.com/0x4272616E646F6E/homelab"
    githubConfigSecret: actions-runner-secrets
    maxRunners: 5
    minRunners: 1
    containerMode:
      type: "dind"
    template:
      spec: {}
    namespaceOverride: ""
