apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
components:
  - ../../components/nginx-filters
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - namespace.yaml
  - falco/
  - clamav/
  - tinyauth/
