apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - secrets.enc.yaml
  - pvc.yaml
  - statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml