apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-qbittorrent-https
  namespace: media
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: qbittorrent
          port: 8080
  tls: 
    secretName: hosted-fail-tls

