apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: qbittorrent
  app.kubernetes.io/managed-by: flux
resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - httproute.yaml
  - networkpolicy.yaml
