# renovate: registryUrl=https://clickhouse.github.io/ClickStack-helm-charts
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickstack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: clickstack
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: clickstack
        namespace: flux-system
  interval: 15m
  timeout: 10m
  releaseName: clickstack
  valuesFrom:
  - kind: ConfigMap
    name: clickstack-config-map
    valuesKey: values.yaml
