apiVersion: v1
kind: Secret
metadata:
    name: clickstack-secrets
    namespace: monitoring
type: Opaque
stringData:
    hyperdx-api-key: ENC[AES256_GCM,data:oVf1S5/asN4cbt0xVI/oYk4dc+LFwYxgBHW1qTdHzST7FyUq,iv:OyfFOFKHY3nIPgLnJ5fnQGgppa4GLWVK3OQ5TRQZYk4=,tag:UFk/Ngt5jxcY6ofKqKq0bQ==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNlY1SXpyTjlBdnFyNjdN
            Yi9xc2U1TkVOOGtpUEZqV2loQUpVSzdPTVE4CndHakh2ZmkxbWl0NFJSbEFwbDdz
            TFJSbUo5UkZhYnZ0aXhyR01DcUpaUXMKLS0tIExkcndQZzFYMkdicS9hNnpKeFVS
            TkJhN1ova0VRUVZhdGJLazJjWE1BQUEK4DD4BOnyD3ElR3HPVa6bxBhqnBsq1B9S
            SAH4WMn84SboUPyZRwaaeKajsyXrqBF6KwrNvJqrNc/Rfn0HjvqW6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T18:52:30Z"
    mac: ENC[AES256_GCM,data:7Ww7dPrYoe0o29pe6baE5geJTZz5MygAhgqGrLB4y9OGfQOEBAuRYkntX/hGkVZhXJLyubVSrIZZpIRKeivA474UqdCmssmnenZWkNTEzKkNmkW7b2zlP1hyjMaFXjliec/djK0fJJ9AB+FI+8WYiZklCYz7zU0BNwojpj2cqLs=,iv:epYveCyujLILnbEf0BEe6mIpg3j+izzn4xyBez4MiFg=,tag:jn6Tao5WB8qRtgnALL6geg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
