apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  # - secrets.sop.yaml 
  - configmap.yaml
  - helmrelease.yaml
  - cilium-loadbalancer-ip-pool.yaml
  - cilium-l2announcement-policy.yaml