apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: flux
components:
  - ../../components/nginx-filters
resources:
  - runtimeclass.yaml
  - local-path-provisioner/
  - cilium/
  - coredns/
  - kubelet-csr-approver/
  - intel-gpu-plugin/
  - nvidia-device-plugin/
  - metrics-server/
  - talos-debug/
  # - maintenance/
