apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-data
  namespace: development
  labels:
    app.kubernetes.io/name: forgejo-runner
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 64Gi
