apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secrets
    namespace: development
type: Opaque
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:yi0NpvryuOhz3zm2wjl+BFJ0E0v0Uztpe/JAlGl7A+Con4bHDSwWJg==,iv:1YNwJqi9xepP/rZflv7Bxe/fJRxweUzA7ZkRTd29OJ4=,tag:gb8NfxwmZFM4/ui7oMsivw==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVTRHc3FIc0djb2FQR0t3
            SUJuTkkwZXpXRmg3eDhjWkh5WHlpdjJ3YzJnCmdXcjRxc3pJZTVtU0lOL0FQOVJT
            eHR1cFdzWEJzV0VBN2JzVEY4VTFJMlUKLS0tIHhTSncyWVl0RzNNMlIvbWk0eld4
            N2QwTmdtNVVaeTFLWG1vTGp5eHJSVXcK7pQENaD3g+oCVgHSMgnTcFfZBvetMiBk
            l2T1QWTDwJ/cz274C8s2NWakZQ2EnVkEkW3osZU4Gi+k7bMtfnEJpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T03:09:12Z"
    mac: ENC[AES256_GCM,data:/r+YBIsamL0EXjStJBe3tXLxaUiEwhfMOYtxeyFczyBAQcno8aBOEldqDFiR7hWszGAGvszAuTNc7BbCD8Q5URsW3pkpNBIraWvLgyecy+8ChThGgA4NCMaS76j2IGgt+bBa0Ma4emReD1ygGq5lCaQDDRxln/pz1hzESQODXtI=,iv:Y5vqtCtilTg20Q0OwsuuUF15d8zjCkWlGP4Xushv4xs=,tag:qXw1ckI8COGCH6Tj0D/0FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
