apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos-debug
  namespace: kube-system
  labels:
    app.kubernetes.io/name: talos-debug
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: talos-debug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: talos-debug
    spec:
      nodeName: talos-4m3-8nj
      securityContext:
        runAsUser: 0
      automountServiceAccountToken: false
      containers:
      - name: talos-debug
        # renovate: datasource=docker depName=docker.io/debian
        image: docker.io/debian:13@sha256:c71b05eac0b20adb4cdcc9f7b052227efd7da381ad10bb92f972e8eae7c6cdc9
        command: ["sh", "-c", "echo 'host debug pod ready'; sleep 36000"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostroot
          mountPath: /host
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
            ephemeral-storage: "5Gi"
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
