apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llamacpp-model-pvc
  namespace: development
  labels:
    app.kubernetes.io/name: llamacpp-model
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 20Gi
