apiVersion: v1
kind: Service
metadata:
  name: llamacpp-model
  namespace: development
  labels:
    app.kubernetes.io/name: llamacpp-model
spec:
  ports:
  - name: llamacpp-model
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: llamacpp-embedding
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: llamacpp-reranker
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app.kubernetes.io/name: llamacpp-model
  sessionAffinity: None
  type: ClusterIP
