apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
  namespace: fileshare
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8000Gi
  storageClassName: local-path-rwx
