apiVersion: v1
kind: ConfigMap
metadata:
  name: reloader-config-map
  namespace: kube-service
data:
  values.yaml: |-
    global:
      imageRegistry: ""
      imagePullSecrets: []
    kubernetes:
      host: https://kubernetes.default
    nameOverride: ""
    fullnameOverride: ""
    image:
      name: stakater/reloader
      repository: ghcr.io/stakater/reloader
      pullPolicy: IfNotPresent
    reloader:
      autoReloadAll: true
      isArgoRollouts: false
      isOpenshift: false
      ignoreSecrets: false
      ignoreConfigMaps: false
      ignoreJobs: false
      ignoreCronJobs: false
      reloadOnCreate: true
      reloadOnDelete: false
      syncAfterRestart: false
      reloadStrategy: default
      ignoreNamespaces: ""
      namespaceSelector: ""
      resourceLabelSelector: ""
      logFormat: "json"
      logLevel: info
      watchGlobally: true
      enableHA: true
      enablePProf: false
      pprofAddr: ":6060"
      readOnlyRootFileSystem: true
      legacy:
        rbac: false
      matchLabels: {}
      enableMetricsByNamespace: false
      deployment:
        dnsConfig: {}
        replicas: 2
        revisionHistoryLimit: 2
        nodeSelector:
        affinity: {}
        volumeMounts: []
        volumes: []
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        tolerations: []
        topologySpreadConstraints: []
        annotations: {}
        labels:
          provider: stakater
          group: com.stakater.platform
          version: v1.4.7
        env:
          open:
          secret:
          field:
          existing:
        livenessProbe:
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          timeoutSeconds: 10
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        pod:
          annotations: {}
        priorityClassName: ""
        gomaxprocsOverride: ""
        gomemlimitOverride: ""
      service:
        {}
      rbac:
        enabled: true
        labels: {}
      serviceAccount:
        create: true
        labels: {}
        annotations: {}
        name:
      custom_annotations: {}
      serviceMonitor:
        enabled: true
        labels: {}
        annotations: {}
        honorLabels: true
        metricRelabelings: []
        relabelings: []
        targetLabels: []
      podMonitor:
        enabled: false
        labels: {}
        annotations: {}
        honorLabels: true
        metricRelabelings: []
        relabelings: []
        podTargetLabels: []
      podDisruptionBudget:
        enabled: false
      netpol:
        enabled: false
        from: []
        to: []
      verticalPodAutoscaler:
        enabled: false
        controlledResources: []
        maxAllowed: {}
        minAllowed: {}
        updatePolicy:
          updateMode: Auto
      webhookUrl: ""
