# renovate: registryUrl=https://stakater.github.io/stakater-charts
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-service
spec:
  chart:
    spec:
      chart: reloader
      version: 2.2.8
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: reloader
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: reloader-config-map
    valuesKey: values.yaml
