apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - pvc.yaml
  - configmap.yaml
  - helmrelease.yaml
  - service.yaml
  - ingress-route.yaml
