apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: snowflake
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
