apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-prowlarr-https
  namespace: media
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: prowlarr
          port: 9696
  tls: 
    secretName: hosted-fail-tls

