apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  # - secrets.sop.yaml 
  - configmap.yaml
  - helmrelease.yaml
  - issuers/letsencrypt-staging.yaml
  - issuers/letsencrypt-production.yaml
  - certificate.yaml