apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/egress: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/egress: wireguard
    spec:
      runtimeClassName: youki
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-nzbget
          # renovate: datasource=docker depName=docker.io/busybox
          image: docker.io/busybox:1.37.0@sha256:e3652a00a2fabd16ce889f0aa32c38eec347b997e73bd09e69c962ec7f8732ee
          imagePullPolicy: IfNotPresent
          command: ["sh","-c"]
          args:
            - |
              set -e
              echo "[init] pre-creating folder tree and fixing ownership"
              mkdir -p /init/downloads/complete /init/downloads/incomplete
              mkdir -p /init/media/movies /init/media/tvshows /init/media/leaving-soon
              chown -R 1000:1000 /init
              chmod -R 777 /init
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: media
              mountPath: /init
      containers:
        - name: nzbget
          # renovate: datasource=docker depName=lscr.io/linuxserver/nzbget
          image: lscr.io/linuxserver/nzbget:latest@sha256:ac2762012e5d4c98da301ffa46d06cbd745273519778b9794884a5d513a0a2ca
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 6789
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: media
          persistentVolumeClaim:
            claimName: media
