apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/egress: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/egress: wireguard
    spec:
      runtimeClassName: youki
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      automountServiceAccountToken: false
      initContainers:
        - name: init-nzbget
          # renovate: datasource=docker depName=docker.io/busybox
          image: docker.io/busybox:1.37.0@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
          imagePullPolicy: IfNotPresent
          command: ["sh","-c"]
          args:
            - |
              set -e
              echo "[init] pre-creating folder tree and fixing ownership"
              mkdir -p /init/downloads/complete /init/downloads/incomplete
              mkdir -p /init/media/movies /init/media/tvshows /init/media/leaving-soon
              chown -R 1000:1000 /init
              chmod -R 777 /init
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: media
              mountPath: /init
      containers:
        - name: nzbget
          # renovate: datasource=docker depName=lscr.io/linuxserver/nzbget
          image: lscr.io/linuxserver/nzbget:latest@sha256:c96d3a5c7876d183b82ee164dd2f8a56d85ee533cd41113dfb9dca6408f191a8
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 6789
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
              ephemeral-storage: "20Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: media
          persistentVolumeClaim:
            claimName: media
