apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
components:
  - ../../components/nginx-filters
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - namespace.yaml
  - renovate/
  - buildkit/
  - code-server/
  - forgejo/
  - forgejo-runner/
  - pr-agent/
  - sonarqube/
  - actions-runner-controller/
  - actions-runner/
  - llamacpp/
  - librechat/
  - localstack/
