apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - namespace.yaml
  - renovate/
  - buildkit/
  - code-server/
  - forgejo/
  - sonarqube/
  - actions-runner-controller/
  - actions-runner/
  - llamacpp/
  - librechat/
  - localstack/
