apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: development
  labels:
    app.kubernetes.io/name: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 5Gi
