apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: development
type: Opaque
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:AYPNzEo0sTKg7/GTBoyVjQZ5ZDOfsdCZxePQY90bI6Q=,iv:6TgyerzCXhv8Feij7NUqZk7bftux4AkumZozFBWLAlE=,tag:cd8EME54kWm24NuqKbZDhA==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b3puamIxakMvWklLNThi
            cStaRi9yTTE4cFJyUUpWUklaaWwrcUcxVVZRCk05anpMOGRoSzlsOWs4MlpKaU85
            bmtEUjF4OWFWbXRhbXFob2tYNEhrMXcKLS0tIDRxS1NVMEs0cFlBeFNzN1pnRXlS
            aVdPWTFwYVQ0czdJWW4xcDV0SDlmUVkKu4ziB7cuPrgdVNSXxsbE/I/bdj3GjVxC
            SO3eXumPtTFSxxqGpwQ9BgNNt8PrB8q/686pDVwrH0wIIpHJb+0pyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T20:52:29Z"
    mac: ENC[AES256_GCM,data:uPI9cfwId2xikbY2wNyKz9DbsQRLNo0knPUYr1YZxqIfDEWTzkvvV8kAFlDDz5WXzbdOE1Ujz2l8ntCYRe0iIS6aK2TfLRgNqhG21CE1KHbG6PDzXs2/Y4B+9Em2i0s+KReAn5+Dr9MjrFsZFMMQnh/xVqi/70yxJu3Esu+eXu0=,iv:1ZcimqFJZT2gTbnYCs6rGki8LwY7VuRMuSBmRlddjPI=,tag:0u3VPovQ1C1Rsbl3mntBvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
