apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-https
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hubble.oglesby.io`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
      services:
        - name: hubble-ui
          port: 80
  tls: 
    secretName: oglesby-io-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-http
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hubble.oglesby.io`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: redirect-https
          namespace: ingress
      services:
        - name: hubble-ui
          port: 80
