apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - configmap.yaml
  - helmrelease.yaml
  - cilium-loadbalancer-ip-pool.yaml
  - cilium-l2announcement-policy.yaml
  - poddisruptionbudget.yaml
