apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pr-agent-config
  namespace: development
  labels:
    app.kubernetes.io/name: pr-agent
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 8Gi
