apiVersion: v1
kind: Secret
metadata:
    name: pr-agent-secrets
    namespace: development
type: Opaque
stringData:
    GITEA_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:QSyNMnlepydhVG717XPMusso/sZh0l8xxTDqAr+ADcoSL4F49iqGQw==,iv:ITDhxba3nIpprybzp9xVSQ0ygqDzJhDUNvMsLwFyksU=,tag:JO5wBNNG7qFygn5mxA2guQ==,type:str]
    GITEA_WEBHOOK_SECRET: ENC[AES256_GCM,data:4YjfQsNRuSAz2iUwgf8QWm7ETU9Xq9fnBPv0nytkoOmdC6sNtj8lJnAdZzYhXJKXKix7iIcYAybizWiGYnkGdQ==,iv:qcZrjBSQ9G+hVo2g67ZaopkPVGYwsNtAxvECLLB1aks=,tag:VEoHX8iU13bWIXXVpTmcNg==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL0RKcFpvWjkxdklHN1E0
            K2ZJdTRLTW9JQ2pvTnExVDB5SWo1TWkwU0RzClh3dmI4MGVBQ1J3d3pMYU9zUCtl
            L3NqUWl2enlCKzRNTENzRk9BcjJPNUEKLS0tIER3NEorcVdwRXoyeGM4MHpQQ1FS
            aGRhLzVDS0Y4d0RBZDBBZGhhQWJlMkUKBgfWbYvHJZf5VWvut7DXK2OSvD57j7hX
            JRgKdDzrcY4BtjheNPKG0CRF9eMsHgT8lVrYU1l4a/6T5tCn5EeUsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T02:18:39Z"
    mac: ENC[AES256_GCM,data:Wavu3iNIapRTas52+VtcmV6eCDeI3wlElVfKOmmgDEZt1smTNhlNwLbYkgezXSroKMaqZ9I7IYKtJjkMslIbBm/QTvTtgzQk/0NP/ROVpFS2th5Pu7VG1Y11ky22IjzC4unzguWEDL+SnXwi9g+CqR15/YS4UDUI5Unl7WB59lo=,iv:FycoP63AOMYqXyNrHqAQASH1cKgAfuuVveJZQRwAzKc=,tag:LCSjvJJ77t2KYz5V8uFlbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
