apiVersion: v1
kind: Secret
metadata:
    name: pr-agent-secrets
    namespace: development
type: Opaque
stringData:
    GITEA_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:CpI5MsddoaasF9IY380Y1VHY7/afufgFZXicpjZStQtmVPOAJi6k1Q==,iv:IUmztu4mUVQrx4hLlbnttR3rigWiukneg582y4HSon8=,tag:Rzo6i26yAvUMeKzB/WswOQ==,type:str]
    GITEA_WEBHOOK_SECRET: ENC[AES256_GCM,data:OmyQMeUWwQSVsUiF4HgQoqaovYZ29N9+Buwq0KuMW0d/8HwvaK1k9dIyU7X3uYBqIVDs95JXdsd2gOS6Fgr4MQ==,iv:ptwill46R4PwugTUSKS809uv51D7mrQvbh01uBS+f1Q=,tag:cnBYw7Owt0gItSAhk7SykA==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkekp0YllhbGRiUDlWTUcy
            VWhTbHQxbkxoUm1FT2UzbERCc0dhOFo1Q3owCnQ3dzd4NU5CczMxNWZUZDNXN0FU
            TnVTcUtrZ2VXU1d5OVgwQ1pNNklFelkKLS0tIHNBVlVncGtGbEJFS3RDTnA1K1Zz
            czl6ejdRUUFyRDNOMDdVVE5UMWdHUG8K5e88qW1ZPkeaEOuHcV6tSQdSXfSLhGDP
            qIcgusLSWe8kJrFMp3cpHPfSClXISPa+ywWzGkM/4I4VTHklVAG8zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T03:17:42Z"
    mac: ENC[AES256_GCM,data:9LCniS8MkvoRiTTALqkGh5f0SB1QyZSNGmDLI5O5f3IErQVXWkqqm2gZ80JLl/7WAmbW/iEA0TyjGCakwx4NdY2v+ARgdxYIrVXPBe3JyGrIL1QIEYZR9sMM1tQhLXikiIAmtmyrQ1RhiMfBjNfqovN4+9ss1QYRb69eTMAPTug=,iv:g4DgunHfhtAoOq69DX4F2ZyNKNGR4BBfVun9fRRDM0U=,tag:27/R9o/JCY4pMBym2+agGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
