apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbot
  namespace: default
  labels:
    app.kubernetes.io/name: redbot
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redbot
        app.kubernetes.io/managed-by: flux
    spec:
      runtimeClassName: youki
      automountServiceAccountToken: false
      containers:
        - name: redbot
          # renovate: datasource=docker depName=docker.io/phasecorex/red-discordbot
          image: docker.io/phasecorex/red-discordbot:core@sha256:2a4a4c853564706a32897c1778eb98ce6fe337ed9c374030e84455f999020de0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "5Gi"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: redbot-secrets
                  key: TOKEN
            - name: PREFIX
              value: "!"
          volumeMounts:
            - name: config
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: redbot-config
