apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-coder-pvc
  namespace: development
  labels:
    app.kubernetes.io/name: vllm-qwen-coder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 20Gi
