apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen-coder
  namespace: development
  labels:
    app.kubernetes.io/name: vllm-qwen-coder
spec:
  ports:
  - name: vllm-qwen-coder
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: vllm-qwen-coder
  sessionAffinity: None
  type: ClusterIP
