apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  namespace: media
  labels:
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tdarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tdarr
        app.kubernetes.io/managed-by: flux
    spec:
      runtimeClassName: nvidia
      securityContext:
        supplementalGroups:
          - 44
      automountServiceAccountToken: false
      containers:
        - name: tdarr
          # renovate: datasource=docker depName=ghcr.io/haveagitgat/tdarr
          image: ghcr.io/haveagitgat/tdarr:latest@sha256:20a5656c4af4854e1877046294f77113f949d27e35940a9a65f231423d063207
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8265
              protocol: TCP
            - containerPort: 8266
              protocol: TCP
          env:
            - name: UMASK_SET
              value: "002"
            - name: serverIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: serverPort
              value: "8266"
            - name: webUIPort
              value: "8265"
            - name: internalNode
              value: "true"
            - name: inContainer
              value: "true"
            - name: ffmpegVersion
              value: "7"
            - name: nodeName
              value: "InternalNode"
            - name: auth
              value: "false"
            - name: openBrowser
              value: "false"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: TZ
              value: "UTC"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            requests:
              cpu: "1000m"
              memory: "4096Mi"
              nvidia.com/gpu: "1"
              ephemeral-storage: "10Gi"
            limits:
              cpu: "2000m"
              memory: "8192Mi"
              nvidia.com/gpu: "1"
              ephemeral-storage: "20Gi"
          volumeMounts:
            - name: config
              mountPath: /app/configs
            - name: server
              mountPath: /app/server
            - name: logs
              mountPath: /app/logs
            - name: media
              mountPath: /media
              subPath: media
            - name: temp
              mountPath: /temp
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tdarr-config
        - name: server
          persistentVolumeClaim:
            claimName: tdarr-server
        - name: logs
          persistentVolumeClaim:
            claimName: tdarr-logs
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: temp
          persistentVolumeClaim:
            claimName: tdarr-temp
