apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tdarr-https
  namespace: media
  labels:
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tdarr.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: tdarr
          port: 8265
  tls:
    secretName: hosted-fail-tls

