apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-code-server-https
  namespace: development
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vscode.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: code-server
          port: 8080
  tls: 
    secretName: hosted-fail-tls
