# renovate: registryUrl=https://helm.kestra.io/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kestra
  namespace: development
spec:
  chart:
    spec:
      chart: kestra
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: kestra
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: kestra
  valuesFrom:
  - kind: ConfigMap
    name: kestra-config-map
    valuesKey: values.yaml
