apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-sonarr-https
  namespace: media
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: sonarr
          port: 8989
  tls: 
    secretName: hosted-fail-tls
