apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestrr
  namespace: media
  labels:
    app.kubernetes.io/name: requestrr
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: requestrr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: requestrr
        app.kubernetes.io/managed-by: flux
    spec:
      runtimeClassName: youki
      automountServiceAccountToken: false
      containers:
        - name: requestrr
          # renovate: datasource=docker depName=docker.io/thomst08/requestrr
          image: docker.io/thomst08/requestrr:latest@sha256:2c01ead0c1eefbf205a819da024c619ae6b0702c7981a1790fc91298d5061c33
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 4545
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 4545
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4545
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 4545
            failureThreshold: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
              ephemeral-storage: "5Gi"
          volumeMounts:
            - name: config
              mountPath: /root/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: requestrr-config
