apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 4m
  path: "./namespace/traefik"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  dependsOn:
    - name: kube-system
    - name: cert-manager
    - name: reflector