apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-jellyfin-https
  namespace: media
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
      services:
        - name: jellyfin
          port: 8096
  tls: 
    secretName: hosted-fail-tls
