apiVersion: v1
kind: ConfigMap
metadata:
  name: kubelet-csr-approver-config-map
  namespace: kube-system
data:
  values.yaml: |-
    # Kubelet CSR Approver Configuration - Only Custom Values
    # Chart defaults are used for all other settings

    providerRegex: "talos-4m3-8nj"
    maxExpirationSeconds: "86400"
    providerIpPrefixes:
      - 10.0.0.250/32
    leaderElection: false
    replicas: 1
