apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: development
  labels:
    app.kubernetes.io/name: buildkit
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: buildkit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildkit
        app.kubernetes.io/managed-by: flux
    spec:
      automountServiceAccountToken: false
      containers:
      - name: buildkitd
        # renovate: datasource=docker depName=docker.io/moby/buildkit
        image: docker.io/moby/buildkit:latest@sha256:1e110c71d389d6d24f67b9438e2f7b8da749a6ff407b22a1631e025c95599368
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        args:
        - "--addr"
        - "tcp://0.0.0.0:1234"
        - "--root"
        - "/cache"
        ports:
        - containerPort: 1234
          name: buildkit
        startupProbe:
          tcpSocket:
            port: 1234
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1234
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 1234
          failureThreshold: 3
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "20Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
            ephemeral-storage: "50Gi"
        volumeMounts:
        - name: cache
          mountPath: /cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: buildkit-cache
