apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: development
  labels:
    app.kubernetes.io/name: buildkit
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: buildkit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildkit
        app.kubernetes.io/managed-by: flux
    spec:
      automountServiceAccountToken: false
      containers:
      - name: buildkitd
        # renovate: datasource=docker depName=docker.io/moby/buildkit
        image: docker.io/moby/buildkit:latest@sha256:de10faf919fc71ba4eb1dd7bd6449566d012b0c9436b1c61bfee21d621b009aa
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        args:
        - "--addr"
        - "tcp://0.0.0.0:1234"
        - "--root"
        - "/cache"
        ports:
        - containerPort: 1234
          name: buildkit
        resources:
          requests:
            cpu: "1"
            memory: "256Mi"
            ephemeral-storage: "20Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
            ephemeral-storage: "50Gi"
        volumeMounts:
        - name: cache
          mountPath: /cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: buildkit-cache
