apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: development
  labels:
    app.kubernetes.io/name: buildkit
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: buildkit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildkit
        app.kubernetes.io/managed-by: flux
    spec:
      containers:
      - name: buildkitd
        # renovate: datasource=docker depName=docker.io/moby/buildkit
        image: docker.io/moby/buildkit:latest@sha256:93da6a53287490dd3b35952f73a109654ed9f260f2e6434db925125fa3ac6b2a
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        args:
        - "--addr"
        - "tcp://0.0.0.0:1234"
        - "--root"
        - "/cache"
        ports:
        - containerPort: 1234
          name: buildkit
        resources:
          requests:
            cpu: "1"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: cache
          mountPath: /cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: buildkit-cache
