apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talos-mirror-data
  namespace: development
  labels:
    app.kubernetes.io/name: talos-mirror
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 50Gi
