apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forgejo-https
  namespace: development
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`forgejo.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
      services:
        - name: forgejo-http
          port: 3000
  tls: 
    secretName: hosted-fail-tls
