apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: development
  labels:
    app.kubernetes.io/name: forgejo
spec:
  selector:
    app.kubernetes.io/name: forgejo
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: forgejo-http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: forgejo-ssh
  type: ClusterIP
