apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: development
  labels:
    app.kubernetes.io/name: forgejo
spec:
  selector:
    app.kubernetes.io/name: forgejo
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: forgejo-http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh
  namespace: development
  labels:
    app.kubernetes.io/name: forgejo
  annotations:
    io.cilium/lb-ipam-ips: "10.0.0.248"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: forgejo
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
