apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-bazarr-https
  namespace: media
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: bazarr
          port: 6767
  tls: 
    secretName: hosted-fail-tls
