apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: proxmox-mirror
  app.kubernetes.io/managed-by: flux
resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - cronjob.yaml
  - service.yaml
  - httproute.yaml
  - networkpolicy.yaml
