apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  namespace: media
  labels:
    app.kubernetes.io/name: wizarr
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wizarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wizarr
        app.kubernetes.io/managed-by: flux
    spec:
      runtimeClassName: youki
      containers:
        - name: wizarr
          # renovate: datasource=docker depName=ghcr.io/wizarrrr/wizarr
          image: ghcr.io/wizarrrr/wizarr:latest@sha256:f2eabe36fcbdb4e8c50fc98b4fe9aa1a00dfcd4411d3ea3f10cf619cf3d83341
          imagePullPolicy: IfNotPresent
          env:
            - name: DISABLE_BUILTIN_AUTH
              value: "true"
          ports:
            - containerPort: 5690
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1500m"
              memory: "1536Mi"
          volumeMounts:
            - name: config
              mountPath: /data/database
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wizarr-config
