apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  namespace: media
  labels:
    app.kubernetes.io/name: wizarr
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wizarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wizarr
        app.kubernetes.io/managed-by: flux
    spec:
      runtimeClassName: youki
      automountServiceAccountToken: false
      containers:
        - name: wizarr
          # renovate: datasource=docker depName=ghcr.io/wizarrrr/wizarr
          image: ghcr.io/wizarrrr/wizarr:latest@sha256:5809c5da07883e3e572b279e41998a6ae93a17f978da899cfe803bc8d7b459fe
          imagePullPolicy: IfNotPresent
          env:
            - name: DISABLE_BUILTIN_AUTH
              value: "true"
          ports:
            - containerPort: 5690
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1500m"
              memory: "1536Mi"
              ephemeral-storage: "5Gi"
          volumeMounts:
            - name: config
              mountPath: /data/database
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wizarr-config
