apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wizarr-https
  namespace: media
  labels:
    app.kubernetes.io/name: wizarr
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wizarr.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: wizarr
          port: 5690
  tls: 
    secretName: hosted-fail-tls
