# renovate: registryUrl=https://SonarSource.github.io/helm-chart-sonarqube
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: development
spec:
  chart:
    spec:
      chart: sonarqube
      version: 2026.1.0
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
  interval: 15m
  timeout: 20m
  releaseName: sonarqube
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
    timeout: 20m
  valuesFrom:
  - kind: ConfigMap
    name: sonarqube-config-map
    valuesKey: values.yaml
