apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: ingress
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Vh133RlxrAftMKPTxlCYNS4sqgE1anwJfBXEFv6jhn7ddE1ryGK0IqpPsoGpSE6YCzBWoXMNPy12XuR35vKi1h+hirDDEvtdfR+kl3BNDFvQe2Reyi0PwZIo0yMTGtvd92yFeAVTFa16uvNN5gnt5fSojWVLXIxk3RCN8H/tARvEVF77RLxYafb6lfAYQIOhY9R6eZ7nmQuMTwPAk43XxSrU60i4+4L4tkdT3DWX4veHQgkGUrnVzE13MVdTZYjI+EsrC4jTy7XmleQCzK7twXglzgLUHg==,iv:+gsyTwRPdsFvqSQfpW5eMlMuG8bOTIPL2RhBQ9T3kiI=,tag:cdNXavtD8C4dLCF/U3TFJA==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQlcrSms0NUFRUlpxLy9F
            UUtPOHdKZWtkZ2RqNlY1WXJjNnk1OVh6RTFrCmdUSFU0THhjSm8rNXNGTFVleG92
            MVBEczRMWkJHellrb1hxY0dnT3FYMWsKLS0tIE5MZzl4ZXNZdGZxOU5WeVVma3ND
            bnA3eG4xSDlmSnA0OWEvVFhCUlBiNzAK2wLT7FB34s2qmy21j7IvfQZZM87ETQjv
            mXtHGpyJ/80+TJv+jFaZZ3wgqgEvDK3bPX/+3nCKILzWLCGukK3aLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T04:10:08Z"
    mac: ENC[AES256_GCM,data:4BOcS16piwm0emgLv5GWBjbAZqj/i7QNPiKFEnKeOWC4vBdENVJ52Z6A5KhtI69gleUIZjBGFfvLE5HTSV9jyIqC68zJ5lYGcgdqEKqRspCgAFxtoEwM6YsJlfxR+hxdBV2lj6N8TOwFnsMLuCSGVbHYALyCswOCgumArkyq3BE=,iv:yWlJ7uJyjSl42K7TqI5fafN6lNz/LkHRTipXBJraTr4=,tag:hQnes/GHM+NUGYkAw1jRKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
