apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-suwayomi-https
  namespace: media
  labels:
    app.kubernetes.io/name: suwayomi
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`suwayomi.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: suwayomi
          port: 4567
  tls: 
    secretName: hosted-fail-tls
