apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: suwayomi
  app.kubernetes.io/managed-by: flux
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - httproute.yaml
  # - networkpolicy.yaml