apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vibe-thinker-pvc
  namespace: development
  labels:
    app.kubernetes.io/name: vllm-vibe-thinker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 20Gi
