apiVersion: v1
kind: Service
metadata:
  name: vllm-vibe-thinker
  namespace: development
  labels:
    app.kubernetes.io/name: vllm-vibe-thinker
spec:
  ports:
  - name: vllm-vibe-thinker
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: vllm-vibe-thinker
  sessionAffinity: None
  type: ClusterIP
