apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tinyauth-https
  namespace: security
  labels:
    app.kubernetes.io/name: tinyauth
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
      services:
        - name: tinyauth
          port: 3000
  tls: 
    secretName: hosted-fail-tls
