apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: pocketid
  app.kubernetes.io/managed-by: flux
resources:
  - secrets.enc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - networkpolicy.yaml
