apiVersion: v1
kind: Secret
metadata:
    name: tinyauth-secrets
    namespace: security
type: Opaque
stringData:
    CREDENTIALS: ENC[AES256_GCM,data:Pwu2ZhBmFWCcN1Fe/bf5bUjjqq+SyAPgIBIdv+DraLvKPS9DGrkR+9ofdGFrFfSXeUrON/wxSHEV+SWA5paSplkI,iv:48iq630+5Qgen4XzWx9GtFxDFi2YJACPTMfOtvAtNaE=,tag:WJRB6KvKwKJ9OFRmp31RJg==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMWxuc21xUkQzdjJoQXJE
            WFlGTmJISVpQMi9BckprRDFWWVFnc3kzOUVjCkdHMlVFQWxEU1dIbzFjbzZNTUdn
            U3Rhdko4dWUzRWZuS0RxSVBMSGZKSkEKLS0tIHM2Z2cxV2kwSHV6NGk2RjFyL1Ez
            WXlqL3lGYnllT0JSUTVnRlM4WUZWWU0KFenF/VGuVQsrUocez62AKT4HjzReLmUY
            W2P+Ay+RaLx+iagBF/y0DbbmFazgcZK6HTLiSQkrrwiE4UYAPYRaEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T19:13:23Z"
    mac: ENC[AES256_GCM,data:qJE5lu8t1RUvqyxS+HyIUuDTtZ6Fbfz3syERS2LoxeW91ypxCfbfF37AaPctjgXczThE2dobN6VuUwq+22lUVdWrZq4LRplMeFLjbsKSeQXFy9OSyO5O7N5JuQ+YTeAXeKAUVoWddaj9agSl5sFNl773By/zM3xk9Z8icBuR6xI=,iv:qB6QZz+8gkCgvHGEFuC59cUKiufP5VUbL311Y+r6BoY=,tag:KpMFZd1W2IBjfQuJDbXm9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
