apiVersion: v1
kind: Service
metadata:
  name: tinyauth
  namespace: security
  labels:
    app.kubernetes.io/name: tinyauth
    app.kubernetes.io/managed-by: flux
spec:
  selector:
    app.kubernetes.io/name: tinyauth
    app.kubernetes.io/managed-by: flux
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: tinyauth
  type: ClusterIP
