apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-operator-config-map
  namespace: kube-system
data:
  values.yaml: |-
    # NVIDIA Device Plugin Configuration - Only Custom Values
    # Chart defaults are used for all other settings
    
    config:
      name: "time-slicing-config-all"
    gfd:
      enabled: true
    runtimeClassName: "nvidia"
