# renovate: registryUrl=https://open-policy-agent.github.io/gatekeeper/charts
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: security
spec:
  chart:
    spec:
      chart: gatekeeper
      version: 3.21.0
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: gatekeeper
  valuesFrom:
  - kind: ConfigMap
    name: gatekeeper-config-map
    valuesKey: values.yaml
