apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-config
  namespace: media
  labels:
    app.kubernetes.io/name: shelfmark
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 8Gi
