apiVersion: v1
kind: Service
metadata:
  name: shelfmark
  namespace: media
  labels:
    app.kubernetes.io/name: shelfmark
    app.kubernetes.io/managed-by: flux
spec:
  selector:
    app.kubernetes.io/name: shelfmark
    app.kubernetes.io/managed-by: flux
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: shelfmark
  type: ClusterIP
