apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apt-mirror-data
  namespace: development
  labels:
    app.kubernetes.io/name: apt-mirror
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 500Gi
