apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/nginx-filters
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - namespace.yaml
  - glance/
  - home-assistant/
  - redbot/
  - steam-headless/
