apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-home
  namespace: development
  labels:
    app.kubernetes.io/name: opencode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 10Gi
