apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation
  namespace: flux-system
spec:
  interval: 4m
  path: "./namespace/automation"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: kube-system