apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - selfsigned-root-ca.yaml
  - selfsigned-intermediate-ca.yaml
  - letsencrypt-wildcard-hosted-fail.yaml
