apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: homeassistant
  namespace: default
  labels:
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/managed-by: flux
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
      app.kubernetes.io/managed-by: flux
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress
      ports:
        - port: 8123
          protocol: TCP
  egress:
    - {}
