apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - configmap.yaml
  - helmrelease.yaml
  - runtimeclass.yaml
  - cuda-time-slicing.yaml