apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: harbor
  app.kubernetes.io/managed-by: flux
resources:
  - pvc.yaml
  - secrets.enc.yaml
  - configmap.yaml
  - helmrelease.yaml
  - httproute.yaml
  - networkpolicy.yaml
