apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-http
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.oglesby.io`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
        - name: redirect-https
      services:
        - name: api@internal
          kind: TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.oglesby.io`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
        - name: authentik
      services:
        - name: api@internal
          kind: TraefikService
