apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-https
  namespace: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
        - name: tinyauth
      services:
        - name: api@internal
          kind: TraefikService
