apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: sunshine-stream-udp
  namespace: ingress
spec:
  entryPoints:
    - sunshine-stream-udp
  routes:
    - services:
        - name: sunshine
          namespace: default
          port: 47984
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: sunshine-stream-tcp
  namespace: ingress
spec:
  entryPoints:
    - sunshine-stream-tcp
  routes:
    - match: "HostSNI(`*`)"
      services:
        - name: sunshine
          namespace: default
          port: 47984
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: sunshine-pairing-tcp
  namespace: ingress
spec:
  entryPoints:
    - sunshine-pairing-tcp
  routes:
    - match: "HostSNI(`*`)"
      services:
        - name: sunshine
          namespace: default
          port: 47989
