apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - daemonset.yaml
  - ciliumegressgatewaypolicy.yaml
