apiVersion: v1
kind: Service
metadata:
  name: llamacpp-gpt-oss
  namespace: development
  labels:
    app.kubernetes.io/name: llamacpp-gpt-oss
spec:
  ports:
  - name: llamacpp-gpt-oss
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: embeddings
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app.kubernetes.io/name: llamacpp-gpt-oss
  sessionAffinity: None
  type: ClusterIP
