apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config-map
  namespace: development
data:
  values.yaml: |-
    replicaCount: 1
    updateStrategy:
      type: Recreate
    image:
      repository: localstack/localstack
      pullPolicy: IfNotPresent
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    extraDeploy: []
    extraAnnotations: {}
    extraLabels: {}
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    role:
      create: true
      annotations: {}
      name: ""
    podLabels: {}
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    debug: false
    command: []
    startServices: "s3,sqs,dynamodb,lambda,apigateway,cloudformation"
    mountDind:
      enabled: false
      forceTLS: true
      image: "docker:29.1-dind@sha256:3a33fc81fa4d38360f490f5b900e9846f725db45bb1d9b1fe02d849bd42a5cf2"
    extraEnvVars:
      - name: DEFAULT_REGION
        value: "us-east-1"
      - name: DEBUG
        value: "0"
      - name: LOCALSTACK_HOST
        value: "localhost.localstack.cloud:4566"
    envFrom: []
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 5
    service:
      type: NodePort
      annotations: {}
      ipFamilies: []
      ipFamilyPolicy: ""
      externalTrafficPolicy: ""
      edgeService:
        name: edge
        targetPort: 4566
        nodePort: 31566
      externalServicePorts:
        start: 4510
        end: 4560
      dnsService:
        enabled: false
        nodePort: 31053
      clusterIP: ""
    ingress:
      enabled: false
      annotations: {}
      ingressClassName: ""
      hosts:
        - host: chart-example.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    persistence:
      enabled: true
      storageClass: "local-path-rwo"
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      dataSource: {}
      existingClaim: ""
      subPath: ""
      ## @param persistence.annotations Annotations to be added to PVC
      annotations: {}
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    lambda:
      executor: "docker"
      image_prefix: "localstack/lambda-"
      environment_timeout: 60
      labels: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    enableStartupScripts: false
    startupScriptContent: ""
    volumes: []
    tests:
      enabled: true
      image:
        repository: amazon/aws-cli
        tag: latest
    volumeMounts: []
