# renovate: registryUrl=https://helm.localstack.cloud
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: localstack
  namespace: development
spec:
  chart:
    spec:
      chart: localstack
      version: 0.6.27
      sourceRef:
        kind: HelmRepository
        name: localstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: localstack
  valuesFrom:
  - kind: ConfigMap
    name: localstack-config-map
    valuesKey: values.yaml
