apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-localstack-https
  namespace: development
  labels:
    app.kubernetes.io/name: localstack
    app.kubernetes.io/managed-by: flux
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`localstack.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
      services:
        - name: localstack
          port: 3080
  tls: 
    secretName: hosted-fail-tls
