apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - selfsigned-bootstrap.yaml
  - selfsigned-root.yaml
  - selfsigned-intermediate.yaml
  - letsencrypt-staging.yaml
  - letsencrypt-production.yaml
