apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-comfyui-https
  namespace: development
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`comfyui.hosted.fail`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: ingress
        - name: tinyauth
          namespace: ingress
      services:
        - name: comfyui
          port: 80
  tls:
    secretName: hosted-fail-tls
