apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: steam-headless
  namespace: default
  labels:
    app.kubernetes.io/name: steam-headless
    app.kubernetes.io/managed-by: flux
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: ingress
      sectionName: https
  hostnames:
    - "steam.hosted.fail"
  rules:
    - filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.nginx.org
            kind: SnippetsFilter
            name: internal-whitelist
      backendRefs:
        - name: steam-headless
          port: 8083
