apiVersion: v1
kind: Secret
metadata:
    name: steam-headless-secrets
    namespace: default
type: Opaque
stringData:
    SUNSHINE_USER: ENC[AES256_GCM,data:J7gHui0=,iv:JDzNx6qUzEfnt9ocWGv0mTCaxRcIYc4CiqPSsh8HF3I=,tag:S8FWV6qDgvtLxJRrQIT39g==,type:str]
    SUNSHINE_PASS: ENC[AES256_GCM,data:GivPxFJnZbkLAnN5OIw=,iv:0/HArI3ZjN4bolv/61v/4n38DTP04AtJsaBhvQS0u2A=,tag:QL6bksvRsJRbvkouzKiv8g==,type:str]
    USER_PASSWORD: ENC[AES256_GCM,data:77LdqaBB9Lg2PhRM6cw=,iv:R5dj9uKz7aS5dO3Yvd0crgiw1r5YcNRvFr3kiZz04+U=,tag:Jd4/g5cp2+UiS3jGHSoQPA==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEczJRbVJCa0Y4QUUxNUda
            ci9ueVhyU1JjTkVHeS8zVUtxRG1hVGxuV1JFClpDUGxOa3JpUXZBTWIzNWNxL2tj
            a1ZUWHA1MWNiVHJMT0txVHlsdzhBUUEKLS0tIHcwSVN0U0ZRK1A4Z2dOMFpBYS9v
            TDBaQW9oV1c1YzRtaG5GVHA5RVlIencKClx8LrKoMc3lnitaA01f94jwNmn/4+qS
            0KXbTe9cSBrSO3MMEDidJeUaJga+5/ey4bJZ5gyW9X+C9u8ioqe7OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T18:06:50Z"
    mac: ENC[AES256_GCM,data:mhbNrS2fOCKsLWPfaNmVnFll2lYAeY/JiaNiXUm/eHa2l/jgSbxR6zA5SGgeij1ORB+3dov+KmAobo88+DbdD7y0HJvzwY1VQJLYhkTN3TsJtgpbjTd+TXiqAHrloXxQrJmFrlmkswnN50MxK3YckpoJAhXPpc2UJSgdKAB260k=,iv:m8udt6hGOMffK/HNv8eJbpmgLPKsgPTUuMFDq2m6ZHo=,tag:vOG3GBRlk6QHXIzv1xPdfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
