apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube-postgres-17
  namespace: development
  labels:
    app.kubernetes.io/name: sonarqube-postgres-17
  annotations:
    kustomize.toolkit.fluxcd.io/force: "enabled"
spec:
  serviceName: sonarqube-postgres-17
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarqube-postgres-17
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarqube-postgres-17
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres
        # renovate: datasource=docker depName=docker.io/postgres
        image: docker.io/postgres:17.7@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "sonarqube"
        - name: POSTGRES_USER
          value: "sonarqube"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: 200m
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      labels:
        app.kubernetes.io/name: sonarqube-postgres-17
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path-rwo"
      resources:
        requests:
          storage: 10Gi
