# renovate: datasource=docker depName=ghcr.io/danny-avila/librechat-chart/librechat
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librechat
  namespace: development
spec:
  chart:
    spec:
      chart: librechat
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: librechat
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: librechat
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: librechat-config-map
    valuesKey: values.yaml
