apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - crds.yaml
  - configmap.yaml
  - helmrelease.yaml
  - toolbox.yaml
  - cluster.yaml
  - ingress-route.yaml
  - operator-patch.yaml
patchesStrategicMerge:
  - operator-patch.yaml