apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config-map
  namespace: development
data:
  values.yaml: |-
    image:
      repository: ghcr.io/mend/renovate-ce
      useFull: true
      pullPolicy: IfNotPresent
    nameOverride: ""
    fullnameOverride: ""
    renovate:
      extraEnvVars: [ ]
      mendRnvAcceptTos: "y"
      mendRnvLicenseKey:
      mendRnvPlatform: "github"
      mendRnvEndpoint: "https://api.github.com/"
      mendRnvGitlabPat:
      mendRnvGithubAppId:
      mendRnvGithubBotUserId:
      mendRnvGithubAppKey:
      mendRnvBitbucketUser:
      mendRnvBitbucketPat:
      mendRnvWebhookURL:
      mendRnvAdminToken:
      mendRnvSqliteFilePath: '/tmp/renovate/renovate-ce.sqlite'
      mendRnvUserAgent:
      mendRnvServerApiSecret:
      mendRnvAdminApiEnabled:
      mendRnvApiEnabled:
      mendRnvSystemApiEnabled:
      mendRnvJobsApiEnabled:
      mendRnvReportingEnabled:
      mendRnvReportingApiEnabled:
      mendRnvWebhookSecret:
      mendRnvWebhookSkipDisabledRepoJobs:
      githubComToken:
      pipIndexUrl:
      existingSecret: "renovate-secrets"
      mendRnvCronJobSchedulerAll:
      mendRnvCronAppSync:
      mendRnvSyncOnStartup:
      mendRnvSyncMode:
      mendRnvLogHistoryS3:
      mendRnvAutoDiscoverFilter:
      mendRnvEnqueueJobsOnStartup:
      mendRnvLogHistoryDir:
      mendRnvLogHistoryTTLDays:
      mendRnvLogHistoryCleanupCron:
      mendRnvForksProcessing:
      mendRnvWorkerExecutionTimeout:
      mendRnvWorkerCleanup: off
      mendRnvWorkerCleanupDirs:
      mendRnvDiskUsageWarnThreshold:
      mendRnvDiskUsageFilter:
      mendRnvWorkerNodeArgs:
      mendRnvPrometheusMetricsEnabled:
      mendRnvDisableGlobalAgent:
      mendRnvEnableHttp2:
      mendRnvHttpServerDisabled:
      mendRnvServerHttpsConfig:
      mendRnvServerHttpsConfigPath:
      config: |
        module.exports = {
          // Enter self-hosted configuration options here.
          // https://docs.renovatebot.com/self-hosted-configuration/
        }
      npmrcExistingSecret:
      noNodeTlsVerify: false
      noGitTlsVerify: false
      renovateUserAgent:
      logLevel: info
      logFormat: json
    postgresql:
      enabled: false
      host:
      port:
      database:
      user:
      password:
    disableCacheVolume: false
    cachePersistence:
      enabled: false
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      existingClaim: ""
    cacheInMemory:
      enabled: false
    service:
      type: ClusterIP
      ports:
        http: 80
        https: 443
      annotations: { }
    ingress:
      enabled: false
      annotations: { }
      hosts:
        { }
      tls: [ ]
    serviceAccount:
      create: false
      existingName:
      annotations: { }
    resources: { }
    annotations: { }
    labels:
      pods: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    podSecurityContext: { }
    containerSecurityContext: { }
    initContainers: [ ]
    imagePullSecrets: ""
    terminationGracePeriodSeconds: 60
    livenessProbe:
      initialDelaySeconds: 2
      httpGet:
        path: /health
        port: http
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      httpGet:
        path: /health
        port: http
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
    extraConfigMaps: [ ]
    extraEnvFromConfigMaps: [ ]
    extraVolumes: [ ]
    extraVolumeMounts: [ ]
