apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - namespace.yaml
  - cert-manager/
  - wireguard/
  - reflector/
  - reloader/
  - knative-operator/
  # - autoscaler/
