---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: default
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: bookmarks
                groups:
                  - links:
                      - title: Bazarr
                        url: https://bazarr.hosted.fail/
                      - title: Code Server
                        url: https://vscode.hosted.fail/
                      - title: Forgejo
                        url: https://forgejo.hosted.fail/
                      - title: Grafana
                        url: https://grafana.hosted.fail/
                      - title: Home Assistant
                        url: https://homeassistant.hosted.fail/
                      - title: Huntarr
                        url: https://huntarr.hosted.fail/
                      - title: Jellyfin
                        url: https://jellyfin.hosted.fail/
                      - title: JellySeerr
                        url: https://jellyseerr.hosted.fail/
                      - title: LibreChat
                        url: https://librechat.hosted.fail/
                      - title: NzbGet
                        url: https://nzbget.hosted.fail/
                      - title: Prometheus
                        url: https://prometheus.hosted.fail/
                      - title: Prowlarr
                        url: https://prowlarr.hosted.fail/
                      - title: Proxmox Backup Server
                        url: https://pve.hosted.fail:8007/
                      - title: Proxmox VE
                        url: https://pve.hosted.fail:8006/
                      - title: Qbittorrent
                        url: https://qbittorrent.hosted.fail/
                      - title: Radarr
                        url: https://radarr.hosted.fail/
                      - title: Requestrr
                        url: https://requestrr.hosted.fail/
                      - title: Sonarr
                        url: https://sonarr.hosted.fail/
                      - title: SonarQube
                        url: https://sonarqube.hosted.fail/
                      - title: Suwayomi
                        url: https://suwayomi.hosted.fail/
                      - title: Traefik
                        url: https://traefik.hosted.fail/
                      - title: UNAS
                        url: https://unas.hosted.fail/
                      - title: Unifi
                        url: https://unifi.hosted.fail/
                      - title: Wizarr
                        url: https://wizarr.hosted.fail/
          - size: full
            widgets:
              - type: rss
                limit: 10
                collapse-after: 3
                cache: 12h
                feeds:
                  - url: https://deepmind.com/blog/feed/basic
                    title: DeepMind
                    limit: 4
                  - url: https://distrowatch.com/news/news-headlines.xml
                    title: Distrowatch
                    limit: 4
                  - url: http://news.ycombinator.com/rss
                    title: Hacker News
                    limit: 4
                  - url: https://kubernetes.io/feed.xml
                    title: Kubernetes
                    limit: 4
                  - url: https://selfh.st/rss/
                    title: selfh.st
                    limit: 4
              - type: videos
                channels:
                  - UC2WHjPDvbE6O328n17ZGcfg # Forrest Knight
                  - UC8butISFwT-Wl7EV0hUK0BQ # Free Code Camp
                  - UCCMi6F5Ac3kQDfffWXQGZDw # Guided Hacking
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UClcE-kVhqyiHCcjYwcpfj9w # Live Overflow
              - type: split-column
                widgets:
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true
                  - type: reddit
                    subreddit: terraform
                    show-thumbnails: true
                  - type: reddit
                    subreddit: kubernetes
                    show-thumbnails: true
                  - type: reddit
                    subreddit: localllama
                    show-thumbnails: true
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday
              - type: weather
                location: Edgewater, Florida, United States
                units: imperial
                hour-format: 24h
              - type: releases
                collapse-after: 99
                cache: 1d
                repositories:
                  - fluxcd/flux2
                  - kubernetes/kubernetes
                  - siderolabs/talos
