apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/nginx-filters
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - namespace.yaml
  - pvc.yaml
  - flaresolverr/
  - qbittorrent/
  - nzbget/
  - prowlarr/
  - bazarr/
  - radarr/
  - sonarr/
  - jellyfin/
  - tdarr/
  - jellyseerr/
  - requestrr/
  - huntarr/
  - wizarr/
  - suwayomi/
