apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/nginx-filters
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - namespace.yaml
  - pvc.yaml
  - flaresolverr/
  - qbittorrent/
  - nzbget/
  - prowlarr/
  - bazarr/
  - radarr/
  - sonarr/
  - jellyfin/
  - tdarr/
  - seerr/
  - requestrr/
  - wizarr/
  - suwayomi/
  - shelfmark/
