apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
components:
  - ../../components/nginx-filters
resources:
  - namespace.yaml
  - clickstack/
  - otel-k8s/
