apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: ingress
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.hosted.fail"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.hosted.fail"
      tls:
        mode: Terminate
        certificateRefs:
          - name: hosted-fail-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
    - name: ssh
      protocol: TCP
      port: 22
      allowedRoutes:
        namespaces:
          from: All
    - name: syslog-udp
      protocol: UDP
      port: 514
      allowedRoutes:
        namespaces:
          from: All
    - name: sunshine-https
      protocol: TCP
      port: 47984
      allowedRoutes:
        namespaces:
          from: All
    - name: sunshine-http
      protocol: TCP
      port: 47989
      allowedRoutes:
        namespaces:
          from: All
    - name: sunshine-rtsp
      protocol: TCP
      port: 47990
      allowedRoutes:
        namespaces:
          from: All
    - name: sunshine-tcp
      protocol: TCP
      port: 48010
      allowedRoutes:
        namespaces:
          from: All
    - name: sunshine-video
      protocol: UDP
      port: 47998
      allowedRoutes:
        namespaces:
          from: All
    - name: sunshine-control
      protocol: UDP
      port: 47999
      allowedRoutes:
        namespaces:
          from: All
    - name: sunshine-audio
      protocol: UDP
      port: 48000
      allowedRoutes:
        namespaces:
          from: All
