# renovate: registryUrl=oci://ghcr.io/nginx/charts/nginx-gateway-fabric
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: ingress
spec:
  chart:
    spec:
      chart: ngf
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nginx-gateway-fabric
  valuesFrom:
  - kind: ConfigMap
    name: nginx-gateway-fabric-config-map
    valuesKey: values.yaml
