apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - gateway-api-crds.yaml
  - security-headers.yaml
  - configmap.yaml
  - helmrelease.yaml
  - gateway.yaml
  - redirect.yaml
  - servicemonitor.yaml
  - poddisruptionbudget.yaml
