apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/managed-by: flux
    includeSelectors: false
resources:
  - gateway-api-crds.yaml
  - security-headers.yaml
  - configmap.yaml
  - helmrelease.yaml
  - gateway.yaml
  - redirect.yaml
  - poddisruptionbudget.yaml
