apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway-fabric
  namespace: ingress
  labels:
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/managed-by: flux
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
