apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: media
  labels:
    app.kubernetes.io/name: seerr
    app.kubernetes.io/managed-by: flux
spec:
  selector:
    app.kubernetes.io/name: seerr
    app.kubernetes.io/managed-by: flux
  ports:
    - port: 5055
      targetPort: 5055
      protocol: TCP
      name: seerr
  type: ClusterIP
