apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-pvc
  namespace: development
  labels:
    app.kubernetes.io/name: vllm-gpt-oss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 20Gi
